services:
  - type: web
    name: goaitracker
    runtime: docker
    plan: free
    region: frankfurt
    branch: main
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: APP_KEY
        sync: false
      - key: DB_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: AI_PROVIDER
        value: groq
      - key: AI_MODEL
        value: llama-3.3-70b-versatile
      - key: AI_API_KEY
        sync: false
      - key: SENTRY_LARAVEL_DSN
        sync: false
